#!/usr/bin/env python3
import argparse
import re
from pathlib import Path

def main():
    p = argparse.ArgumentParser(description="Pack levels with RLE compression and generate Tile LUT")
    p.add_argument("input", type=Path, help="input file (mappings + levels)")
    p.add_argument("tiles_asm", type=Path, help="tiles assembly file for indices")
    p.add_argument("output", type=Path, help="output assembly file")
    args = p.parse_args()

    # 1. Read ASM Indices
    asm_indices = {}
    for line in args.tiles_asm.read_text(encoding="utf-8").splitlines():
        m = re.match(r'^(\w+)_Index\s+equ\s+(\d+)', line.strip(), re.I)
        if m:
            asm_indices[m.group(1)] = int(m.group(2))

    # 2. Parse Mappings, Build LUT, and Parse Levels
    mappings = {}

    flag_needs_redraw = 0x40
    flag_pushable = 0x80

    tile_lut = [{
        "info": tile_index | flag_needs_redraw,
        "name": ""
    } for tile_index in range(32)]  # 32-byte Lookup Table for the 8085
    levels = []     # List of tuples: (level_name, list_of_rows)

    raw_lines = args.input.read_text(encoding="utf-8").splitlines()
    lines = [line.split(';')[0].strip() for line in raw_lines]
    lines = [line for line in lines if line]

    i = 0
    while i < len(lines):
        line = lines[i]

        if '=' in line:
            # Parse mapping: . = TileEmpty #pushable #player
            char, rest = line.split('=', 1)
            char = char.strip()
            parts = rest.split()
            name = parts[0]
            tags = set(parts[1:])

            if name not in asm_indices:
                raise ValueError(f"Unknown tile in ASM: {name}")

            tile_id = asm_indices[name]
            if tile_id > 31:
                raise ValueError(f"Tile ID {tile_id} exceeds 5-bit limit (max 31)")

            # Populate the 8085 LUT for this tile ID
            tile_lut[tile_id]["name"] = name;
            if '#pushable' in tags:
                tile_lut[tile_id]["info"] |= flag_pushable

            # Save mapping for the level parser
            mappings[char] = {'id': tile_id, 'is_player': '#player' in tags}
            i += 1

        else:
            # Parse level header and grid
            level_name = re.sub(r'[^0-9A-Za-z_]', '_', line)
            rows = lines[i+1 : i+9]

            if len(rows) < 8 or any(len(r) != 24 for r in rows):
                raise ValueError(f"Level '{level_name}' grid must be exactly 24x8")

            levels.append((level_name, rows))
            i += 9 # Skip header + 8 rows

    # 3. Generate Output Assembly
    out = []

    out.append(";-------------------------------------------------------------------------------")
    out.append("; This file was generated by tools/levels2asm.py")
    out.append(";-------------------------------------------------------------------------------")
    out.append("")

    out.append(";-------------------------------------------------------------------------------")
    out.append("LevelLookupTable:")
    out.append("; Maps Level Index -> Pointer to Level Data")
    out.append(";-------------------------------------------------------------------------------")
    for idx, (name, _) in enumerate(levels):
        out.append(f"    dw {name} ; Level {idx}")
    out.append("")

    # Emit the 32-byte LUT first
    out.append(";-------------------------------------------------------------------------------")
    out.append("TileInfoFromTileIndexMap:")
    out.append("; Pre-baked RAM bytes: [Pushable][Dirty][0][TileID 0-4]")
    out.append(";-------------------------------------------------------------------------------")
    for tile in tile_lut:
        out.append(f"    db 0b{tile["info"]:08b} ; {tile["name"]}")
    out.append("")

    # Process and compress each level
    for name, rows in levels:
        out.append(";-------------------------------------------------------------------------------")
        out.append(f"{name}:")
        out.append(";-------------------------------------------------------------------------------")
        out.append(".TileData:")

        compressed_bytes = []
        px, py = None, None

        current_id = None
        run_count = 0

        # Helper to pack and emit the current run
        def flush_run():
            if run_count > 0:
                # Top 3 bits: (count - 1), Bottom 5 bits: Tile ID
                packed_byte = ((run_count - 1) << 5) | current_id
                compressed_bytes.append(packed_byte)

        # Traverse Column-Major (x outer, y inner)
        for x in range(24):
            for y in range(8):
                char = rows[y][x]
                if char not in mappings:
                    raise ValueError(f"Unknown char '{char}' in level '{name}'")

                tile = mappings[char]
                tile_id = tile['id']

                if tile['is_player']:
                    px, py = x, y

                # RLE Logic: Match found and count is under 8
                if current_id == tile_id and run_count < 8:
                    run_count += 1
                else:
                    # Tile changed OR hit the 8-tile limit, flush and start new run
                    flush_run()
                    current_id = tile_id
                    run_count = 1

        # Flush the very last run at the end of the level
        flush_run()

        # Emit compressed bytes in readable chunks
        for j in range(0, len(compressed_bytes), 12):
            chunk = compressed_bytes[j:j+12]
            out.append("    db " + ", ".join(f"0x{b:02x}" for b in chunk))

        out.append("")
        if px is not None:
            out.append(f".PlayerStartY: db {py}")
            out.append(f".PlayerStartX: db {px}")
        out.append("")

    # Write to disk
    args.output.write_text("\n".join(out), encoding="utf-8")

    # Calculate savings
    raw_size = len(levels) * 24 * 8
    compressed_size = sum(len(lvl_bytes) for _, lvl_bytes in [(n, out) for n in out if "db 0b" in n]) # Rough string estimation
    print(f"Successfully packed {len(levels)} levels.")
    print(f"Total LUT size: 32 bytes.")

if __name__ == "__main__":
    main()