; Generated by png2asm.py

;---------------------------------------
TileEmpty_Index equ 0
TileEmpty:
	db 0b00000000
	db 0b00000000
	db 0b00000000
	db 0b00000000
	db 0b00000000
	db 0b00000000
	db 0b00000000
	db 0b00000000
	db 0b00000000
	db 0b00000000

;---------------------------------------
TileEmpty2_Index equ 1
TileEmpty2:
	db 0b00000000
	db 0b00100000
	db 0b00000000
	db 0b00000100
	db 0b00000000
	db 0b00000000
	db 0b00000000
	db 0b00001000
	db 0b00000000
	db 0b00000000

;---------------------------------------
TileHole_Index equ 2
TileHole:
	db 0b01111110
	db 0b11111001
	db 0b11101101
	db 0b11111001
	db 0b11110101
	db 0b11011001
	db 0b11110101
	db 0b11111001
	db 0b11101101
	db 0b01111110

;---------------------------------------
TileGoal_Index equ 3
TileGoal:
	db 0b11111111
	db 0b11111111
	db 0b11111111
	db 0b11111111
	db 0b11111111
	db 0b11111111
	db 0b11111111
	db 0b11111111
	db 0b11111111
	db 0b11111111

;---------------------------------------
TileCrateStone_Index equ 4
TileCrateStone:
	db 0b01111110
	db 0b11111111
	db 0b11101011
	db 0b11010001
	db 0b11000001
	db 0b11001001
	db 0b11000001
	db 0b11100011
	db 0b01111110
	db 0b00000000

;---------------------------------------
TileRightArrow_Index equ 5
TileRightArrow:
	db 0b00000000
	db 0b00011000
	db 0b00011000
	db 0b00011000
	db 0b01011010
	db 0b01111110
	db 0b01111110
	db 0b00111100
	db 0b00011000
	db 0b00000000

;---------------------------------------
TileUpArrow_Index equ 6
TileUpArrow:
	db 0b00000000
	db 0b00000000
	db 0b00011100
	db 0b00001110
	db 0b01111111
	db 0b01111111
	db 0b00001110
	db 0b00011100
	db 0b00000000
	db 0b00000000

;---------------------------------------
TileLeftArrow_Index equ 7
TileLeftArrow:
	db 0b00000000
	db 0b00011000
	db 0b00111100
	db 0b01111110
	db 0b01111110
	db 0b01011010
	db 0b00011000
	db 0b00011000
	db 0b00011000
	db 0b00000000

;---------------------------------------
TileDownArrow_Index equ 8
TileDownArrow:
	db 0b00000000
	db 0b00000000
	db 0b00011100
	db 0b00111000
	db 0b01111111
	db 0b01111111
	db 0b00111000
	db 0b00011100
	db 0b00000000
	db 0b00000000

;---------------------------------------
TileBoxKidRight_Index equ 9
TileBoxKidRight:
	db 0b00111110
	db 0b01011101
	db 0b11000101
	db 0b01000101
	db 0b01011101
	db 0b11000101
	db 0b01010101
	db 0b00111110
	db 0b00010000
	db 0b00000000

;---------------------------------------
TileBoxKidUp_Index equ 10
TileBoxKidUp:
	db 0b00010000
	db 0b00111110
	db 0b01000101
	db 0b11000101
	db 0b01000101
	db 0b01000101
	db 0b11000101
	db 0b01000101
	db 0b00111110
	db 0b00010000

;---------------------------------------
TileBoxKidLeft_Index equ 11
TileBoxKidLeft:
	db 0b00000000
	db 0b00010000
	db 0b00111110
	db 0b01010101
	db 0b11000101
	db 0b01011101
	db 0b01000101
	db 0b11000101
	db 0b01011101
	db 0b00111110

;---------------------------------------
TileBoxKidDown_Index equ 12
TileBoxKidDown:
	db 0b00010000
	db 0b00111110
	db 0b01000101
	db 0b11011101
	db 0b01000101
	db 0b01000101
	db 0b11011101
	db 0b01000101
	db 0b00111110
	db 0b00010000

;---------------------------------------
TileWallBrick_Index equ 13
TileWallBrick:
	db 0b01110111
	db 0b01110111
	db 0b01110000
	db 0b01110111
	db 0b01110111
	db 0b00000111
	db 0b01110111
	db 0b01110111
	db 0b01110111
	db 0b01110111

;---------------------------------------
TileWallBrick2_Index equ 14
TileWallBrick2:
	db 0b01110111
	db 0b01110111
	db 0b01110000
	db 0b00000111
	db 0b01110111
	db 0b01110111
	db 0b01110111
	db 0b01110000
	db 0b00000111
	db 0b01110111

;---------------------------------------
TileWallBrick3_Index equ 15
TileWallBrick3:
	db 0b11011101
	db 0b11010111
	db 0b11011101
	db 0b11011101
	db 0b01111101
	db 0b11011101
	db 0b11010111
	db 0b11011101
	db 0b11011101
	db 0b01111101

